# Default values for composition-portal-starter.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

overview:
  enabled: true
  text: This is going to be the overview text
compositionstatus:
  enabled: true
applicationstatus:
  enabled: true
terminal:
  enabled: false
events:
  enabled: true
yamlviewer:
  enabled: true
finops:
  enabled: false
global:
  compositionApiVersion: compositionApiVersion
  compositionGroup: compositionGroup
  compositionInstalledVersion: compositionInstalledVersion
  compositionId: compositionId
  compositionKind: compositionKind
  compositionName: compositionName
  compositionNamespace: compositionNamespace
  compositionResource: compositionResource
  krateoNamespace: krateoNamespace