kind: Panel
apiVersion: widgets.templates.krateo.io/v1beta1
metadata:
  name: {{ .Release.Name }}-composition-panel
  namespace: {{ .Release.Namespace }}
  labels:
    krateo.io/portal-page: compositions
spec:
  apiRef:
    name: {{ .Release.Name }}-composition-values
    namespace: {{ .Release.Namespace }}
  widgetData:
    clickActionId: composition-click-action
    footer:
      - resourceRefId: composition-panel-button-delete
    tags: 
      - {{ .Release.Namespace }}
      - {{ .Values.global.compositionGroup }}
      - {{ .Values.global.compositionInstalledVersion }}
      - {{ .Values.global.compositionKind }}
      - {{ .Values.global.compositionResource }}
    icon:
      name: fa-solid fa-cubes
      color: blue
    items:
      - resourceRefId: composition-panel-paragraph
    title: {{ .Release.Name }}
    actions:
      navigate:
        - id: composition-click-action
          name: composition-click-action
          resourceRefId: composition-tablist
          type: navigate
  widgetDataTemplate:
    - forPath: icon.color
      expression: ${ ((.values?.status?.conditions // []) | map(select(.type == "Ready") | if .status == "False" then "orange" elif .status == "True" then "green" else "grey" end) | first) // "grey" }
    - forPath: headerLeft
      expression: ${ ((.values?.status?.conditions // []) | map(select(.type == "Ready") | if .status == "False" then "Ready:False" elif .status == "True" then "Ready:True" else "Ready:Unknown" end) | first) // "Ready:Unknown" }
    - forPath: headerRight
      expression: ${ .values // {} | .metadata.creationTimestamp // "In the process of being created" }
  resourcesRefs:
    - id: composition-panel-paragraph
      apiVersion: widgets.templates.krateo.io/v1beta1
      name: {{ .Release.Name }}-composition-panel-paragraph
      namespace: {{ .Release.Namespace }}
      resource: paragraphs
      verb: GET
    - id: composition-panel-button-delete
      apiVersion: widgets.templates.krateo.io/v1beta1
      name: {{ .Release.Name }}-composition-panel-button-delete
      namespace: {{ .Release.Namespace }}
      resource: buttons
      verb: GET
    - id: composition-tablist
      apiVersion: widgets.templates.krateo.io/v1beta1
      name: {{ .Release.Name }}-composition-tablist
      namespace: {{ .Release.Namespace }}
      resource: tablists
      verb: GET