kind: Paragraph
apiVersion: widgets.templates.krateo.io/v1beta1
metadata:
  name: {{ .Release.Name }}-composition-overview-panel-paragraph
  namespace: {{ .Release.Namespace }}
spec:
  widgetData:
    text: {{- $repo := (lookup "github.kog.krateo.io/v1alpha1" "Repo" .Release.Namespace (printf "%s-repo" .Release.Name)) }}
          {{- if $repo }}
          "Target repository: https://github.com/{{ $repo.spec.org }}/{{ $repo.spec.name }}"
          {{- else }}
          "Target repository: in the process of being created"
          {{- end }}
