kind: Paragraph
apiVersion: widgets.templates.krateo.io/v1beta1
metadata:
  name: {{ .Release.Name }}-composition-overview-panel-paragraph
  namespace: {{ .Release.Namespace }}
spec:
  widgetData:
    text: "Target repository: https://github.com/{{ .Values.git.toRepo.org }}/{{ .Values.git.toRepo.name }}"