kind: Paragraph
apiVersion: widgets.templates.krateo.io/v1beta1
metadata:
  name: {{ .Release.Name }}-composition-panel-paragraph
  namespace: {{ .Release.Namespace }}
spec:
  widgetData:
    text: "{{ .Release.Name }} is a {{ .Values.global.compositionResource }} composition of version {{ .Values.global.compositionGroup }}/{{ .Values.global.compositionInstalledVersion }}"