apiVersion: templates.krateo.io/v1
kind: RESTAction
metadata:
  name: {{ .Release.Name }}-composition-values
  namespace: {{ .Release.Namespace }}
spec:
  api:
  - name: getValues
    path: "/apis/{{ .Values.global.compositionApiVersion }}/namespaces/{{ .Release.Namespace }}/{{ .Values.global.compositionResource }}/{{ .Release.Name }}"
    verb: GET
  filter: >
    {
      values: (.getValues | del(.metadata.managedFields) // [])
    }